/**
 * Nationality list for the /apply form.
 *
 * Each entry:
 *   key — canonical English demonym, stored in the DB and posted by the form.
 *   en  — English label shown when the page is in English.
 *   ar  — Arabic label shown when the page is in Arabic.
 *
 * Sorted alphabetically by English name. "Other" is forced to the bottom so
 * applicants who don't see their nationality have a fallback.
 *
 * Adding a new entry? Add it to NATIONALITIES below — the form options and the
 * server-side allow-list are both derived from this single source of truth.
 */

const ENTRIES = [
  { key: 'Afghan',                en: 'Afghan',                ar: 'أفغاني' },
  { key: 'Albanian',              en: 'Albanian',              ar: 'ألباني' },
  { key: 'Algerian',              en: 'Algerian',              ar: 'جزائري' },
  { key: 'American',              en: 'American',              ar: 'أمريكي' },
  { key: 'Andorran',              en: 'Andorran',              ar: 'أندوري' },
  { key: 'Angolan',               en: 'Angolan',               ar: 'أنغولي' },
  { key: 'Antiguan',              en: 'Antiguan',              ar: 'أنتيغي' },
  { key: 'Argentine',             en: 'Argentine',             ar: 'أرجنتيني' },
  { key: 'Armenian',              en: 'Armenian',              ar: 'أرمني' },
  { key: 'Australian',            en: 'Australian',            ar: 'أسترالي' },
  { key: 'Austrian',              en: 'Austrian',              ar: 'نمساوي' },
  { key: 'Azerbaijani',           en: 'Azerbaijani',           ar: 'أذربيجاني' },
  { key: 'Bahamian',              en: 'Bahamian',              ar: 'باهامي' },
  { key: 'Bahraini',              en: 'Bahraini',              ar: 'بحريني' },
  { key: 'Bangladeshi',           en: 'Bangladeshi',           ar: 'بنغلاديشي' },
  { key: 'Barbadian',             en: 'Barbadian',             ar: 'بربادوسي' },
  { key: 'Belarusian',            en: 'Belarusian',            ar: 'بيلاروسي' },
  { key: 'Belgian',               en: 'Belgian',               ar: 'بلجيكي' },
  { key: 'Belizean',              en: 'Belizean',              ar: 'بليزي' },
  { key: 'Beninese',              en: 'Beninese',              ar: 'بنيني' },
  { key: 'Bhutanese',             en: 'Bhutanese',             ar: 'بوتاني' },
  { key: 'Bolivian',              en: 'Bolivian',              ar: 'بوليفي' },
  { key: 'Bosnian',               en: 'Bosnian',               ar: 'بوسني' },
  { key: 'Botswanan',             en: 'Botswanan',             ar: 'بوتسواني' },
  { key: 'Brazilian',             en: 'Brazilian',             ar: 'برازيلي' },
  { key: 'British',               en: 'British',               ar: 'بريطاني' },
  { key: 'Bruneian',              en: 'Bruneian',              ar: 'بروناي' },
  { key: 'Bulgarian',             en: 'Bulgarian',             ar: 'بلغاري' },
  { key: 'Burkinabe',             en: 'Burkinabe',             ar: 'بوركيني' },
  { key: 'Burmese',               en: 'Burmese (Myanmar)',     ar: 'بورمي (ميانمار)' },
  { key: 'Burundian',             en: 'Burundian',             ar: 'بوروندي' },
  { key: 'Cambodian',             en: 'Cambodian',             ar: 'كمبودي' },
  { key: 'Cameroonian',           en: 'Cameroonian',           ar: 'كاميروني' },
  { key: 'Canadian',              en: 'Canadian',              ar: 'كندي' },
  { key: 'Cape Verdean',          en: 'Cape Verdean',          ar: 'رأس أخضري' },
  { key: 'Central African',       en: 'Central African',       ar: 'وسط أفريقي' },
  { key: 'Chadian',               en: 'Chadian',               ar: 'تشادي' },
  { key: 'Chilean',               en: 'Chilean',               ar: 'تشيلي' },
  { key: 'Chinese',               en: 'Chinese',               ar: 'صيني' },
  { key: 'Colombian',             en: 'Colombian',             ar: 'كولومبي' },
  { key: 'Comorian',              en: 'Comorian',              ar: 'قمري' },
  { key: 'Congolese',             en: 'Congolese (Republic)',  ar: 'كونغولي' },
  { key: 'Congolese (DRC)',       en: 'Congolese (DRC)',       ar: 'كونغولي (الديمقراطية)' },
  { key: 'Costa Rican',           en: 'Costa Rican',           ar: 'كوستاريكي' },
  { key: 'Croatian',              en: 'Croatian',              ar: 'كرواتي' },
  { key: 'Cuban',                 en: 'Cuban',                 ar: 'كوبي' },
  { key: 'Cypriot',               en: 'Cypriot',               ar: 'قبرصي' },
  { key: 'Czech',                 en: 'Czech',                 ar: 'تشيكي' },
  { key: 'Danish',                en: 'Danish',                ar: 'دنماركي' },
  { key: 'Djiboutian',            en: 'Djiboutian',            ar: 'جيبوتي' },
  { key: 'Dominican',             en: 'Dominican (Dominica)',  ar: 'دومينيكي (دومينيكا)' },
  { key: 'Dominican (DR)',        en: 'Dominican (Dominican Republic)', ar: 'دومينيكاني (الجمهورية الدومينيكية)' },
  { key: 'Dutch',                 en: 'Dutch',                 ar: 'هولندي' },
  { key: 'East Timorese',         en: 'East Timorese',         ar: 'تيموري' },
  { key: 'Ecuadorian',            en: 'Ecuadorian',            ar: 'إكوادوري' },
  { key: 'Egyptian',              en: 'Egyptian',              ar: 'مصري' },
  { key: 'Emirati',               en: 'Emirati',               ar: 'إماراتي' },
  { key: 'Equatorial Guinean',    en: 'Equatorial Guinean',    ar: 'غيني استوائي' },
  { key: 'Eritrean',              en: 'Eritrean',              ar: 'إريتري' },
  { key: 'Estonian',              en: 'Estonian',              ar: 'إستوني' },
  { key: 'Ethiopian',             en: 'Ethiopian',             ar: 'إثيوبي' },
  { key: 'Fijian',                en: 'Fijian',                ar: 'فيجي' },
  { key: 'Filipino',              en: 'Filipino',              ar: 'فلبيني' },
  { key: 'Finnish',               en: 'Finnish',               ar: 'فنلندي' },
  { key: 'French',                en: 'French',                ar: 'فرنسي' },
  { key: 'Gabonese',              en: 'Gabonese',              ar: 'غابوني' },
  { key: 'Gambian',               en: 'Gambian',               ar: 'غامبي' },
  { key: 'Georgian',              en: 'Georgian',              ar: 'جورجي' },
  { key: 'German',                en: 'German',                ar: 'ألماني' },
  { key: 'Ghanaian',              en: 'Ghanaian',              ar: 'غاني' },
  { key: 'Greek',                 en: 'Greek',                 ar: 'يوناني' },
  { key: 'Grenadian',             en: 'Grenadian',             ar: 'غريناديني' },
  { key: 'Guatemalan',            en: 'Guatemalan',            ar: 'غواتيمالي' },
  { key: 'Guinean',               en: 'Guinean',               ar: 'غيني' },
  { key: 'Guinea-Bissauan',       en: 'Guinea-Bissauan',       ar: 'غيني بيساوي' },
  { key: 'Guyanese',              en: 'Guyanese',              ar: 'غياني' },
  { key: 'Haitian',               en: 'Haitian',               ar: 'هايتي' },
  { key: 'Honduran',              en: 'Honduran',              ar: 'هندوراسي' },
  { key: 'Hong Konger',           en: 'Hong Konger',           ar: 'هونغ كونغي' },
  { key: 'Hungarian',             en: 'Hungarian',             ar: 'مجري' },
  { key: 'Icelandic',             en: 'Icelandic',             ar: 'آيسلندي' },
  { key: 'Indian',                en: 'Indian',                ar: 'هندي' },
  { key: 'Indonesian',            en: 'Indonesian',            ar: 'إندونيسي' },
  { key: 'Iranian',               en: 'Iranian',               ar: 'إيراني' },
  { key: 'Iraqi',                 en: 'Iraqi',                 ar: 'عراقي' },
  { key: 'Irish',                 en: 'Irish',                 ar: 'أيرلندي' },
  { key: 'Israeli',               en: 'Israeli',               ar: 'إسرائيلي' },
  { key: 'Italian',               en: 'Italian',               ar: 'إيطالي' },
  { key: 'Ivorian',               en: 'Ivorian',               ar: 'إيفواري' },
  { key: 'Jamaican',              en: 'Jamaican',              ar: 'جامايكي' },
  { key: 'Japanese',              en: 'Japanese',              ar: 'ياباني' },
  { key: 'Jordanian',             en: 'Jordanian',             ar: 'أردني' },
  { key: 'Kazakhstani',           en: 'Kazakhstani',           ar: 'كازاخستاني' },
  { key: 'Kenyan',                en: 'Kenyan',                ar: 'كيني' },
  { key: 'I-Kiribati',            en: 'I-Kiribati',            ar: 'كيريباتي' },
  { key: 'North Korean',          en: 'North Korean',          ar: 'كوري شمالي' },
  { key: 'South Korean',          en: 'South Korean',          ar: 'كوري جنوبي' },
  { key: 'Kosovan',               en: 'Kosovan',               ar: 'كوسوفي' },
  { key: 'Kuwaiti',               en: 'Kuwaiti',               ar: 'كويتي' },
  { key: 'Kyrgyzstani',           en: 'Kyrgyzstani',           ar: 'قيرغيزستاني' },
  { key: 'Laotian',               en: 'Laotian',               ar: 'لاوسي' },
  { key: 'Latvian',               en: 'Latvian',               ar: 'لاتفي' },
  { key: 'Lebanese',              en: 'Lebanese',              ar: 'لبناني' },
  { key: 'Liberian',              en: 'Liberian',              ar: 'ليبيري' },
  { key: 'Libyan',                en: 'Libyan',                ar: 'ليبي' },
  { key: 'Liechtensteiner',       en: 'Liechtensteiner',       ar: 'ليختنشتايني' },
  { key: 'Lithuanian',            en: 'Lithuanian',            ar: 'ليتواني' },
  { key: 'Luxembourgish',         en: 'Luxembourgish',         ar: 'لوكسمبورغي' },
  { key: 'North Macedonian',      en: 'North Macedonian',      ar: 'مقدوني شمالي' },
  { key: 'Malagasy',              en: 'Malagasy',              ar: 'مدغشقري' },
  { key: 'Malawian',              en: 'Malawian',              ar: 'مالاوي' },
  { key: 'Malaysian',             en: 'Malaysian',             ar: 'ماليزي' },
  { key: 'Maldivian',             en: 'Maldivian',             ar: 'مالديفي' },
  { key: 'Malian',                en: 'Malian',                ar: 'مالي' },
  { key: 'Maltese',               en: 'Maltese',               ar: 'مالطي' },
  { key: 'Marshallese',           en: 'Marshallese',           ar: 'مارشالي' },
  { key: 'Mauritanian',           en: 'Mauritanian',           ar: 'موريتاني' },
  { key: 'Mauritian',             en: 'Mauritian',             ar: 'موريشيوسي' },
  { key: 'Mexican',               en: 'Mexican',               ar: 'مكسيكي' },
  { key: 'Micronesian',           en: 'Micronesian',           ar: 'ميكرونيزي' },
  { key: 'Moldovan',              en: 'Moldovan',              ar: 'مولدوفي' },
  { key: 'Monegasque',            en: 'Monegasque',            ar: 'موناكي' },
  { key: 'Mongolian',             en: 'Mongolian',             ar: 'منغولي' },
  { key: 'Montenegrin',           en: 'Montenegrin',           ar: 'جبل أسود' },
  { key: 'Moroccan',              en: 'Moroccan',              ar: 'مغربي' },
  { key: 'Mozambican',            en: 'Mozambican',            ar: 'موزمبيقي' },
  { key: 'Namibian',              en: 'Namibian',              ar: 'ناميبي' },
  { key: 'Nauruan',               en: 'Nauruan',               ar: 'ناوروي' },
  { key: 'Nepalese',              en: 'Nepalese',              ar: 'نيبالي' },
  { key: 'New Zealander',         en: 'New Zealander',         ar: 'نيوزيلندي' },
  { key: 'Nicaraguan',            en: 'Nicaraguan',            ar: 'نيكاراغوي' },
  { key: 'Nigerien',              en: 'Nigerien (Niger)',      ar: 'نيجيري (النيجر)' },
  { key: 'Nigerian',              en: 'Nigerian (Nigeria)',    ar: 'نيجيري (نيجيريا)' },
  { key: 'Norwegian',             en: 'Norwegian',             ar: 'نرويجي' },
  { key: 'Omani',                 en: 'Omani',                 ar: 'عماني' },
  { key: 'Pakistani',             en: 'Pakistani',             ar: 'باكستاني' },
  { key: 'Palauan',                en: 'Palauan',              ar: 'بالاوي' },
  { key: 'Palestinian',           en: 'Palestinian',           ar: 'فلسطيني' },
  { key: 'Panamanian',            en: 'Panamanian',            ar: 'بنمي' },
  { key: 'Papua New Guinean',     en: 'Papua New Guinean',     ar: 'بابوي' },
  { key: 'Paraguayan',            en: 'Paraguayan',            ar: 'باراغواي' },
  { key: 'Peruvian',              en: 'Peruvian',              ar: 'بيروفي' },
  { key: 'Polish',                en: 'Polish',                ar: 'بولندي' },
  { key: 'Portuguese',            en: 'Portuguese',            ar: 'برتغالي' },
  { key: 'Qatari',                en: 'Qatari',                ar: 'قطري' },
  { key: 'Romanian',              en: 'Romanian',              ar: 'روماني' },
  { key: 'Russian',               en: 'Russian',               ar: 'روسي' },
  { key: 'Rwandan',               en: 'Rwandan',               ar: 'رواندي' },
  { key: 'Saint Kittian',         en: 'Saint Kittian',         ar: 'سانت كيتسي' },
  { key: 'Saint Lucian',          en: 'Saint Lucian',          ar: 'سانت لوسي' },
  { key: 'Saint Vincentian',      en: 'Saint Vincentian',      ar: 'سانت فينسنتي' },
  { key: 'Salvadoran',            en: 'Salvadoran',            ar: 'سلفادوري' },
  { key: 'Samoan',                en: 'Samoan',                ar: 'ساموي' },
  { key: 'San Marinese',          en: 'San Marinese',          ar: 'سان مارينو' },
  { key: 'Sao Tomean',            en: 'Sao Tomean',            ar: 'ساو توميي' },
  { key: 'Saudi',                 en: 'Saudi',                 ar: 'سعودي' },
  { key: 'Senegalese',            en: 'Senegalese',            ar: 'سنغالي' },
  { key: 'Serbian',               en: 'Serbian',               ar: 'صربي' },
  { key: 'Seychellois',           en: 'Seychellois',           ar: 'سيشلي' },
  { key: 'Sierra Leonean',        en: 'Sierra Leonean',        ar: 'سيراليوني' },
  { key: 'Singaporean',           en: 'Singaporean',           ar: 'سنغافوري' },
  { key: 'Slovak',                en: 'Slovak',                ar: 'سلوفاكي' },
  { key: 'Slovenian',             en: 'Slovenian',             ar: 'سلوفيني' },
  { key: 'Solomon Islander',      en: 'Solomon Islander',      ar: 'سليماني' },
  { key: 'Somali',                en: 'Somali',                ar: 'صومالي' },
  { key: 'South African',         en: 'South African',         ar: 'جنوب أفريقي' },
  { key: 'South Sudanese',        en: 'South Sudanese',        ar: 'جنوب سوداني' },
  { key: 'Spanish',               en: 'Spanish',               ar: 'إسباني' },
  { key: 'Sri Lankan',            en: 'Sri Lankan',            ar: 'سريلانكي' },
  { key: 'Sudanese',              en: 'Sudanese',              ar: 'سوداني' },
  { key: 'Surinamese',            en: 'Surinamese',            ar: 'سورينامي' },
  { key: 'Swazi',                 en: 'Swazi (Eswatini)',      ar: 'سوازي (إسواتيني)' },
  { key: 'Swedish',               en: 'Swedish',               ar: 'سويدي' },
  { key: 'Swiss',                 en: 'Swiss',                 ar: 'سويسري' },
  { key: 'Syrian',                en: 'Syrian',                ar: 'سوري' },
  { key: 'Taiwanese',             en: 'Taiwanese',             ar: 'تايواني' },
  { key: 'Tajikistani',           en: 'Tajikistani',           ar: 'طاجيكستاني' },
  { key: 'Tanzanian',             en: 'Tanzanian',             ar: 'تنزاني' },
  { key: 'Thai',                  en: 'Thai',                  ar: 'تايلندي' },
  { key: 'Togolese',              en: 'Togolese',              ar: 'توغولي' },
  { key: 'Tongan',                en: 'Tongan',                ar: 'تونغي' },
  { key: 'Trinidadian',           en: 'Trinidadian',           ar: 'ترينيدادي' },
  { key: 'Tunisian',              en: 'Tunisian',              ar: 'تونسي' },
  { key: 'Turkish',               en: 'Turkish',               ar: 'تركي' },
  { key: 'Turkmen',               en: 'Turkmen',               ar: 'تركماني' },
  { key: 'Tuvaluan',              en: 'Tuvaluan',              ar: 'توفالي' },
  { key: 'Ugandan',               en: 'Ugandan',               ar: 'أوغندي' },
  { key: 'Ukrainian',             en: 'Ukrainian',             ar: 'أوكراني' },
  { key: 'Uruguayan',             en: 'Uruguayan',             ar: 'أوروغواي' },
  { key: 'Uzbekistani',           en: 'Uzbekistani',           ar: 'أوزبكستاني' },
  { key: 'Vanuatuan',             en: 'Vanuatuan',             ar: 'فانواتي' },
  { key: 'Vatican',               en: 'Vatican',               ar: 'فاتيكاني' },
  { key: 'Venezuelan',            en: 'Venezuelan',            ar: 'فنزويلي' },
  { key: 'Vietnamese',            en: 'Vietnamese',            ar: 'فيتنامي' },
  { key: 'Yemeni',                en: 'Yemeni',                ar: 'يمني' },
  { key: 'Zambian',               en: 'Zambian',               ar: 'زامبي' },
  { key: 'Zimbabwean',            en: 'Zimbabwean',            ar: 'زيمبابوي' },
  // Fallback — always last, never sorted.
  { key: 'Other',                 en: 'Other',                 ar: 'آخر' },
]

// "Other" is forced to the bottom; everything else stays alphabetical by English.
export const NATIONALITIES = ENTRIES

// Allow-list used by the server action for validation.
export const NATIONALITY_KEYS = new Set(ENTRIES.map((n) => n.key))

/**
 * Build a {key: label} object for the current language.
 * Used by the form to render <option> elements with localized labels
 * but English values.
 */
export function nationalityOptionsForLang(lang) {
  const out = {}
  for (const n of ENTRIES) {
    out[n.key] = lang === 'ar' ? n.ar : n.en
  }
  return out
}
