# syntax=docker/dockerfile:1.7
# ----------------------------------------------------------------------
# Slook landing — production Dockerfile (Next.js 15, standalone output)
#
# Three stages:
#   1. deps     — install npm deps + compile native modules (better-sqlite3)
#   2. builder  — run `next build` to produce the standalone bundle
#   3. runner   — minimal runtime image (~150 MB) running as non-root user
#
# Build:   docker build -t slook-landing .
# Run:     docker run -p 3000:3000 \
#            -v $(pwd)/data:/app/data \
#            --env-file .env.local \
#            slook-landing
# ----------------------------------------------------------------------

# ============== 1. deps ============================================
FROM node:20-alpine AS deps
# better-sqlite3 needs python3 + a C++ toolchain to compile its .node binary
# on Alpine (musl libc). libc6-compat helps with prebuilt Node binaries.
RUN apk add --no-cache libc6-compat python3 make g++

WORKDIR /app
COPY package.json package-lock.json* ./

# Use `npm ci` when a lockfile is present (reproducible), fall back to install.
RUN if [ -f package-lock.json ]; then \
      npm ci --no-audit --no-fund; \
    else \
      npm install --no-audit --no-fund; \
    fi

# ============== 2. builder =========================================
FROM node:20-alpine AS builder
WORKDIR /app

# Re-export the deps tree so `next build` can resolve everything
COPY --from=deps /app/node_modules ./node_modules
COPY . .

ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=production

RUN npm run build

# ============== 3. runner ==========================================
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

# Non-root user
RUN addgroup --system --gid 1001 nodejs \
 && adduser  --system --uid 1001 nextjs

# Standalone output bundles only the files this app actually needs.
# It already includes a minimal `server.js`, traced node_modules,
# and the native better-sqlite3 binary (because we marked it as
# serverExternalPackages in next.config.mjs).
COPY --from=builder --chown=nextjs:nodejs /app/public        ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static  ./.next/static

# SQLite lives here. Mount as a volume to persist across container restarts.
RUN mkdir -p /app/data && chown -R nextjs:nodejs /app/data
VOLUME ["/app/data"]

USER nextjs
EXPOSE 3001

# `server.js` is generated by Next.js standalone output and starts the app.
CMD ["node", "server.js"]
